# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09cff184f5de919d876b8550d028853ac8ae12bb3304f784f437c64f92a3de7f762792412620c98366f2dcb7d3fc235be926bfc3898bec9aacaa724a9ef5ee6e

test:
  secret_key_base: f776a21c2181575513e98e4900845ccdab6875f6c006846f4bc09dec11dd46ed77bc488552ea5ffda374cdf1177514aac2964c48962e8543c89d17c82e8e2276

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
